name: Publish Package

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      # Ensure npm 11.5.1 or later is installed
      - name: Update npm
        run: npm install -g npm@latest
      - run: npm ci
      - run: npm run build --if-present
      - name: Run tests in CI mode
        run: npm run test:ci --if-present
        env:
          CHROME_BIN: /usr/bin/google-chrome
      - name: Publish to npm
        run: |
          cd dist/nga-inline-calendar
          npm publish --access public --provenance
